<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5b324ded262b6',
	'title' => 'Charts [BLOCK]',
	'fields' => array(
		array(
			'key' => 'field_5bc5bd1d4b0ab',
			'label' => 'Chart Type',
			'name' => 'chart_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'bar' => 'Bar',
				'line' => 'Line',
				'radar' => 'Radar',
				'polarArea' => 'Polar Area',
				'pie' => 'Pie',
				'doughnut' => 'Doughnut',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'bar',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5bc5c1a74b0b1',
			'label' => 'Bar Chart',
			'name' => 'bar_chart',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc5bd1d4b0ab',
						'operator' => '==',
						'value' => 'bar',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5bc5c1eb4b0b2',
					'label' => 'Top Label',
					'name' => 'label',
					'type' => 'text',
					'instructions' => 'This label displays at the top of the Bar Graph',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'e.g. & of votes',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bc5bd9b4b0ac',
					'label' => 'Chart Data',
					'name' => 'chart_data',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_5bc5bdbb4b0ad',
							'label' => 'Labels',
							'name' => 'labels',
							'type' => 'text',
							'instructions' => 'This Label display underneath each Bar.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5bc5bdce4b0ae',
							'label' => 'Data',
							'name' => 'data',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5bc5bde64b0af',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#rr0000',
						),
						array(
							'key' => 'field_5bc5c412b0773',
							'label' => 'Background Color Opacity',
							'name' => 'background_color_opacity',
							'type' => 'range',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 100,
							'min' => '',
							'max' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
					),
				),
				array(
					'key' => 'field_5bc5c440b0774',
					'label' => 'Border Width',
					'name' => 'border_width',
					'type' => 'range',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'min' => '',
					'max' => 10,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_5bc5f1fb24885',
			'label' => 'Line / Radar Chart',
			'name' => 'line_chart',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc5bd1d4b0ab',
						'operator' => '==',
						'value' => 'line',
					),
				),
				array(
					array(
						'field' => 'field_5bc5bd1d4b0ab',
						'operator' => '==',
						'value' => 'radar',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5bc5f1fb24886',
					'label' => 'Top Labels',
					'name' => 'line_labels',
					'type' => 'text',
					'instructions' => 'This label displays at the top of the Line Graph and when user hovers over a Line. <b>Please use comma separated values.</b>',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bc5f1fb2488c',
					'label' => 'Border Width',
					'name' => 'border_width',
					'type' => 'range',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'min' => '',
					'max' => 10,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5bc5f1fb24888',
					'label' => 'Labels',
					'name' => 'labels',
					'type' => 'text',
					'instructions' => 'This Label display underneath each Data Point. (Vertical points on the X-axis.)',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bc5f1fb24887',
					'label' => 'Lines Data Points',
					'name' => 'lines_data_points',
					'type' => 'repeater',
					'instructions' => 'The number of LINES should match the number of TOP Labels.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Line',
					'sub_fields' => array(
						array(
							'key' => 'field_5bc5f1fb24889',
							'label' => 'Data',
							'name' => 'data',
							'type' => 'text',
							'instructions' => 'Comma separated values. <b>The number of Data Points should match the number of labels.</b>',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5bc5f1fb2488a',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#rr0000',
						),
						array(
							'key' => 'field_5bc5f1fb2488b',
							'label' => 'Background Color Opacity',
							'name' => 'background_color_opacity',
							'type' => 'range',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 100,
							'min' => '',
							'max' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_5bc6cbd0c46e9',
			'label' => 'Polar Area / Pie / Doughnut Chart',
			'name' => 'pie_chart',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc5bd1d4b0ab',
						'operator' => '==',
						'value' => 'polarArea',
					),
				),
				array(
					array(
						'field' => 'field_5bc5bd1d4b0ab',
						'operator' => '==',
						'value' => 'pie',
					),
				),
				array(
					array(
						'field' => 'field_5bc5bd1d4b0ab',
						'operator' => '==',
						'value' => 'doughnut',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5bc6cc61a3aea',
					'label' => 'Line Labels',
					'name' => 'line_labels',
					'type' => 'text',
					'instructions' => 'This label displays at the top of the Line Graph and when user hovers over a Line. <b>Please use comma separated values.</b>',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bc6cc04c46f2',
					'label' => 'Data Points',
					'name' => 'data',
					'type' => 'text',
					'instructions' => 'Comma separated values. <b>The number of Data Points should match the number of labels.</b>',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bc6cc04c46f1',
					'label' => 'Lines Data Points',
					'name' => 'lines_data_points',
					'type' => 'repeater',
					'instructions' => 'The number of colors should match the number of Data Points.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Line',
					'sub_fields' => array(
						array(
							'key' => 'field_5bc6cc04c46f3',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#rr0000',
						),
						array(
							'key' => 'field_5bc6cc04c46f4',
							'label' => 'Background Color Opacity',
							'name' => 'background_color_opacity',
							'type' => 'range',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 100,
							'min' => '',
							'max' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/add-chart-in-post',
			),
		),
	),
	'menu_order' => -10,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cf8becc3e837',
	'title' => 'Add Event n Post [BLOCK]',
	'fields' => array(
		array(
			'key' => 'field_5cf8befaaf3ce',
			'label' => 'Add Event',
			'name' => 'add_event',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'event',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/add-event-in-post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cfcc2f65b545',
	'title' => 'Announcement Settings',
	'fields' => array(
		array(
			'key' => 'field_5cfcc30f27dec',
			'label' => 'Start Date',
			'name' => 'start_date',
			'type' => 'date_time_picker',
			'instructions' => 'The announcement will start showing on the date & time provided here.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'U',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5cfcc34827ded',
			'label' => 'End Date',
			'name' => 'end_date',
			'type' => 'date_time_picker',
			'instructions' => 'The announcement will stop showing on the date & time provided here.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'U',
			'first_day' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'announcement',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d4f238f83a92',
	'title' => 'CLONE: Buttons',
	'fields' => array(
		array(
			'key' => 'field_5d4f23a0e7e98',
			'label' => 'Buttons',
			'name' => 'buttons',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Button',
			'sub_fields' => array(
				array(
					'key' => 'field_5d4f2568bdf51',
					'label' => 'Button Link Type',
					'name' => 'btn_link_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'int' => 'Internal',
						'ext' => 'External',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_5d4fb39bdad28',
					'label' => 'Button (Internal Link)',
					'name' => 'btn_int_grp',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d4f2568bdf51',
								'operator' => '==',
								'value' => 'int',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d4f254fbdf50',
							'label' => 'Button (Internal Link)',
							'name' => 'button',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'post_type' => '',
							'taxonomy' => '',
							'allow_null' => 0,
							'allow_archives' => 1,
							'multiple' => 0,
						),
						array(
							'key' => 'field_5d4fb3c7dad2a',
							'label' => 'Button Name',
							'name' => 'btn_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5d4fb403dad2b',
					'label' => 'Button (External Link)',
					'name' => 'btn_ext_grp',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d4f2568bdf51',
								'operator' => '==',
								'value' => 'ext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d4f23aae7e99',
							'label' => 'Button (External Link)',
							'name' => 'button',
							'type' => 'url',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5d4fb403dad2d',
							'label' => 'Button Name',
							'name' => 'btn_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d53b3dfece11',
	'title' => 'Committee Members Page',
	'fields' => array(
		array(
			'key' => 'field_5d53b561fff34',
			'label' => 'Members',
			'name' => 'members',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5d53b57dfff36',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Member',
			'sub_fields' => array(
				array(
					'key' => 'field_5d53b57dfff36',
					'label' => 'Name',
					'name' => 'name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d53b588fff37',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpeg,jpg',
				),
				array(
					'key' => 'field_5d53b3e01a69c',
					'label' => 'Designation',
					'name' => 'designation',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d53b3e01ae7c',
					'label' => 'Social Links',
					'name' => 'social_icons',
					'type' => 'clone',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'clone' => array(
						0 => 'group_5be1a0ef0d211',
					),
					'display' => 'group',
					'layout' => 'block',
					'prefix_label' => 1,
					'prefix_name' => 1,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'committee_members',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'pg-templates/committee-members.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d6ff31b33198',
	'title' => 'Contact Details',
	'fields' => array(
		array(
			'key' => 'field_5d6ff329f7601',
			'label' => 'Address',
			'name' => 'address',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5d6ff33bf7602',
			'label' => 'Contact Numbers',
			'name' => 'contact_numbers',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Contact Number',
			'sub_fields' => array(
				array(
					'key' => 'field_5d6ff361f7603',
					'label' => 'Contact Number',
					'name' => 'contact_number',
					'type' => 'clone',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'clone' => array(
						0 => 'group_5cf75bafe2e2d',
					),
					'display' => 'group',
					'layout' => 'block',
					'prefix_label' => 1,
					'prefix_name' => 1,
				),
			),
		),
		array(
			'key' => 'field_5d6ff386f7604',
			'label' => 'VO Number',
			'name' => 'vo_number',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cf75bafe2e2d',
	'title' => 'Contact Number [CLONE]',
	'fields' => array(
		array(
			'key' => 'field_5cf75bb6a70e0',
			'label' => 'Country Code',
			'name' => 'cc',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				213 => 'Algeria (+213)',
				376 => 'Andorra (+376)',
				244 => 'Angola (+244)',
				1264 => 'Anguilla (+1264)',
				1268 => 'Antigua &amp; Barbuda (+1268)',
				54 => 'Argentina (+54)',
				374 => 'Armenia (+374)',
				297 => 'Aruba (+297)',
				61 => 'Australia (+61)',
				43 => 'Austria (+43)',
				994 => 'Azerbaijan (+994)',
				1242 => 'Bahamas (+1242)',
				973 => 'Bahrain (+973)',
				880 => 'Bangladesh (+880)',
				1246 => 'Barbados (+1246)',
				375 => 'Belarus (+375)',
				32 => 'Belgium (+32)',
				501 => 'Belize (+501)',
				229 => 'Benin (+229)',
				1441 => 'Bermuda (+1441)',
				975 => 'Bhutan (+975)',
				591 => 'Bolivia (+591)',
				387 => 'Bosnia Herzegovina (+387)',
				267 => 'Botswana (+267)',
				55 => 'Brazil (+55)',
				673 => 'Brunei (+673)',
				359 => 'Bulgaria (+359)',
				226 => 'Burkina Faso (+226)',
				257 => 'Burundi (+257)',
				855 => 'Cambodia (+855)',
				237 => 'Cameroon (+237)',
				1 => 'USA (+1)',
				238 => 'Cape Verde Islands (+238)',
				1345 => 'Cayman Islands (+1345)',
				236 => 'Central African Republic (+236)',
				56 => 'Chile (+56)',
				86 => 'China (+86)',
				57 => 'Colombia (+57)',
				269 => 'Mayotte (+269)',
				242 => 'Congo (+242)',
				682 => 'Cook Islands (+682)',
				506 => 'Costa Rica (+506)',
				385 => 'Croatia (+385)',
				53 => 'Cuba (+53)',
				90392 => 'Cyprus North (+90392)',
				357 => 'Cyprus South (+357)',
				42 => 'Czech Republic (+42)',
				45 => 'Denmark (+45)',
				253 => 'Djibouti (+253)',
				1809 => 'Dominican Republic (+1809)',
				593 => 'Ecuador (+593)',
				20 => 'Egypt (+20)',
				503 => 'El Salvador (+503)',
				240 => 'Equatorial Guinea (+240)',
				291 => 'Eritrea (+291)',
				372 => 'Estonia (+372)',
				251 => 'Ethiopia (+251)',
				500 => 'Falkland Islands (+500)',
				298 => 'Faroe Islands (+298)',
				679 => 'Fiji (+679)',
				358 => 'Finland (+358)',
				33 => 'France (+33)',
				594 => 'French Guiana (+594)',
				689 => 'French Polynesia (+689)',
				241 => 'Gabon (+241)',
				220 => 'Gambia (+220)',
				7880 => 'Georgia (+7880)',
				49 => 'Germany (+49)',
				233 => 'Ghana (+233)',
				350 => 'Gibraltar (+350)',
				30 => 'Greece (+30)',
				299 => 'Greenland (+299)',
				1473 => 'Grenada (+1473)',
				590 => 'Guadeloupe (+590)',
				671 => 'Guam (+671)',
				502 => 'Guatemala (+502)',
				224 => 'Guinea (+224)',
				245 => 'Guinea - Bissau (+245)',
				592 => 'Guyana (+592)',
				509 => 'Haiti (+509)',
				504 => 'Honduras (+504)',
				852 => 'Hong Kong (+852)',
				36 => 'Hungary (+36)',
				354 => 'Iceland (+354)',
				91 => 'India (+91)',
				62 => 'Indonesia (+62)',
				98 => 'Iran (+98)',
				964 => 'Iraq (+964)',
				353 => 'Ireland (+353)',
				972 => 'Israel (+972)',
				39 => 'Italy (+39)',
				1876 => 'Jamaica (+1876)',
				81 => 'Japan (+81)',
				962 => 'Jordan (+962)',
				7 => 'Uzbekistan (+7)',
				254 => 'Kenya (+254)',
				686 => 'Kiribati (+686)',
				850 => 'Korea North (+850)',
				82 => 'Korea South (+82)',
				965 => 'Kuwait (+965)',
				996 => 'Kyrgyzstan (+996)',
				856 => 'Laos (+856)',
				371 => 'Latvia (+371)',
				961 => 'Lebanon (+961)',
				266 => 'Lesotho (+266)',
				231 => 'Liberia (+231)',
				218 => 'Libya (+218)',
				417 => 'Liechtenstein (+417)',
				370 => 'Lithuania (+370)',
				352 => 'Luxembourg (+352)',
				853 => 'Macao (+853)',
				389 => 'Macedonia (+389)',
				261 => 'Madagascar (+261)',
				265 => 'Malawi (+265)',
				60 => 'Malaysia (+60)',
				960 => 'Maldives (+960)',
				223 => 'Mali (+223)',
				356 => 'Malta (+356)',
				692 => 'Marshall Islands (+692)',
				596 => 'Martinique (+596)',
				222 => 'Mauritania (+222)',
				52 => 'Mexico (+52)',
				691 => 'Micronesia (+691)',
				373 => 'Moldova (+373)',
				377 => 'Monaco (+377)',
				976 => 'Mongolia (+976)',
				1664 => 'Montserrat (+1664)',
				212 => 'Morocco (+212)',
				258 => 'Mozambique (+258)',
				95 => 'Myanmar (+95)',
				264 => 'Namibia (+264)',
				674 => 'Nauru (+674)',
				977 => 'Nepal (+977)',
				31 => 'Netherlands (+31)',
				687 => 'New Caledonia (+687)',
				64 => 'New Zealand (+64)',
				505 => 'Nicaragua (+505)',
				227 => 'Niger (+227)',
				234 => 'Nigeria (+234)',
				683 => 'Niue (+683)',
				672 => 'Norfolk Islands (+672)',
				670 => 'Northern Marianas (+670)',
				47 => 'Norway (+47)',
				968 => 'Oman (+968)',
				680 => 'Palau (+680)',
				507 => 'Panama (+507)',
				675 => 'Papua New Guinea (+675)',
				595 => 'Paraguay (+595)',
				51 => 'Peru (+51)',
				63 => 'Philippines (+63)',
				48 => 'Poland (+48)',
				351 => 'Portugal (+351)',
				1787 => 'Puerto Rico (+1787)',
				974 => 'Qatar (+974)',
				262 => 'Reunion (+262)',
				40 => 'Romania (+40)',
				250 => 'Rwanda (+250)',
				378 => 'San Marino (+378)',
				239 => 'Sao Tome &amp; Principe (+239)',
				966 => 'Saudi Arabia (+966)',
				221 => 'Senegal (+221)',
				381 => 'Serbia (+381)',
				248 => 'Seychelles (+248)',
				232 => 'Sierra Leone (+232)',
				65 => 'Singapore (+65)',
				421 => 'Slovak Republic (+421)',
				386 => 'Slovenia (+386)',
				677 => 'Solomon Islands (+677)',
				252 => 'Somalia (+252)',
				27 => 'South Africa (+27)',
				34 => 'Spain (+34)',
				94 => 'Sri Lanka (+94)',
				290 => 'St. Helena (+290)',
				1869 => 'St. Kitts (+1869)',
				1758 => 'St. Lucia (+1758)',
				249 => 'Sudan (+249)',
				597 => 'Suriname (+597)',
				268 => 'Swaziland (+268)',
				46 => 'Sweden (+46)',
				41 => 'Switzerland (+41)',
				963 => 'Syria (+963)',
				886 => 'Taiwan (+886)',
				66 => 'Thailand (+66)',
				228 => 'Togo (+228)',
				676 => 'Tonga (+676)',
				1868 => 'Trinidad &amp; Tobago (+1868)',
				216 => 'Tunisia (+216)',
				90 => 'Turkey (+90)',
				993 => 'Turkmenistan (+993)',
				1649 => 'Turks &amp; Caicos Islands (+1649)',
				688 => 'Tuvalu (+688)',
				256 => 'Uganda (+256)',
				44 => 'UK (+44)',
				380 => 'Ukraine (+380)',
				971 => 'United Arab Emirates (+971)',
				598 => 'Uruguay (+598)',
				678 => 'Vanuatu (+678)',
				379 => 'Vatican City (+379)',
				58 => 'Venezuela (+58)',
				84 => 'Virgin Islands - US (+1340)',
				681 => 'Wallis &amp; Futuna (+681)',
				969 => 'Yemen (North)(+969)',
				967 => 'Yemen (South)(+967)',
				260 => 'Zambia (+260)',
				263 => 'Zimbabwe (+263)',
			),
			'default_value' => array(
				0 => 356,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5cf75bf3a70e1',
			'label' => 'Number',
			'name' => 'number',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 21123456,
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cf3b6068f43c',
	'title' => 'Custom Category Archives',
	'fields' => array(
		array(
			'key' => 'field_5cf3d9a91576d',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g. Latest Articles on {category-name}',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cf3d1ecc1b85',
			'label' => 'Width',
			'name' => 'width',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full' => 'Full Width',
				'half' => 'Half Width',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5cf3d9e51576e',
			'label' => 'Number of Posts',
			'name' => 'num_of_posts',
			'type' => 'number',
			'instructions' => 'Number of posts to display. Min: 1; Max: 10.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 5,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 10,
			'step' => 1,
		),
		array(
			'key' => 'field_5cf3bbd4a33c8',
			'label' => 'Custom Category Archive',
			'name' => 'custom_category_archive',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'checkbox',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/custom-category-archives',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cf3df7c15c00',
	'title' => 'Custom Tag Archives',
	'fields' => array(
		array(
			'key' => 'field_5cf3df7c422a6',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g. Latest Articles on {tag-name}',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cf3df7c426a9',
			'label' => 'Width',
			'name' => 'width',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full' => 'Full Width',
				'half' => 'Half Width',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5cf3df7c42a7c',
			'label' => 'Number of Posts',
			'name' => 'num_of_posts',
			'type' => 'number',
			'instructions' => 'Number of posts to display. Min: 1; Max: 10.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 5,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 10,
			'step' => 1,
		),
		array(
			'key' => 'field_5cf3df7c42e74',
			'label' => 'Custom Tag Archive',
			'name' => 'custom_tag_archive',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'post_tag',
			'field_type' => 'checkbox',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/custom-tag-archives',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c586f0bdb48e',
	'title' => 'Events',
	'fields' => array(
		array(
			'key' => 'field_5d20c0a4d869f',
			'label' => 'Note:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'If inserting <b>Multiple Dates</b>, please make sure to set <i>Start Date</i> and <i>End Date</i> the same as the <b>first</b> and <b>last</b> date entered in the <b>Multiple Dates</b> selections.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5c586f149c8f0',
			'label' => 'Start Date',
			'name' => 'start_date',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y H:i',
			'return_format' => 'U',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5c5870704b34a',
			'label' => 'End Date',
			'name' => 'end_date',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y H:i',
			'return_format' => 'U',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5d20bc569c124',
			'label' => 'Select Individual Dates',
			'name' => 'select_individual_dates',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Date',
			'sub_fields' => array(
				array(
					'key' => 'field_5d20bc739c125',
					'label' => 'Start Date',
					'name' => 'start_date',
					'type' => 'date_time_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y H:i',
					'return_format' => 'U',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5d20bd0b911a7',
					'label' => 'End Date',
					'name' => 'end_date',
					'type' => 'date_time_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y H:i',
					'return_format' => 'U',
					'first_day' => 1,
				),
			),
		),
		array(
			'key' => 'field_5c587edadede8',
			'label' => 'Speaker',
			'name' => 'speaker',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'speaker',
			),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'object',
			'ui' => 1,
		),
		array(
			'key' => 'field_5c5870b84b34b',
			'label' => 'Venue',
			'name' => 'venue',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'venue',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array(
			'key' => 'field_5c58721bf337a',
			'label' => 'Admittance',
			'name' => 'admittance',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'All Ages|Kulħadd' => 'All Ages|Kulħadd',
				'All Ages/Licensed|Kulħadd/Liċenzja' => 'All Ages/Licensed|Kulħadd/Liċenzja',
				'18+|18+' => '18+|18+',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'array',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c587273f337b',
			'label' => 'Price',
			'name' => 'price',
			'type' => 'number',
			'instructions' => 'in Euros',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5c587295f337c',
			'label' => 'Ticket Url',
			'name' => 'ticket_url',
			'type' => 'url',
			'instructions' => 'Must start with <b>https://</b> or <b>https://</b>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c5872abf337d',
			'label' => 'Ticket Phone',
			'name' => 'contact_number',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5cf75bafe2e2d',
			),
			'display' => 'group',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5c5872c9f337e',
			'label' => 'Notes',
			'name' => 'notes',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'event',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d1edf9e62efc',
	'title' => 'Front Page [Flex]',
	'fields' => array(
		array(
			'key' => 'field_5d1edfa4779b0',
			'label' => 'Add Content',
			'name' => 'add_content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_5d1edfb5dba25' => array(
					'key' => 'layout_5d1edfb5dba25',
					'name' => 'full_text_editor',
					'label' => 'Full Text Editor',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1ef9bfd80e5',
							'label' => 'Section Properties',
							'name' => 'sec_prop',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5d1ef968d72a5',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 1,
							'prefix_name' => 1,
						),
						array(
							'key' => 'field_5d1edfdd779b1',
							'label' => 'WYSIWYG',
							'name' => 'wysiwyg',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d1ee16bbfbd1' => array(
					'key' => 'layout_5d1ee16bbfbd1',
					'name' => 'join_application_form',
					'label' => 'How to Join / Application Form',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1efa2f74bd6',
							'label' => 'Section Properties',
							'name' => 'sec_prop',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5d1ef968d72a5',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 1,
							'prefix_name' => 1,
						),
						array(
							'key' => 'field_5d1ee37dbfbd3',
							'label' => 'WYSIWYG',
							'name' => 'wysiwyg',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_5d1ee372bfbd2',
							'label' => 'Application Form',
							'name' => 'application_form',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'page',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'allow_archives' => 0,
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d1ee8c1bfbd4' => array(
					'key' => 'layout_5d1ee8c1bfbd4',
					'name' => 'donations',
					'label' => 'Donations',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1efa4d74bd7',
							'label' => 'Section Properties',
							'name' => 'sec_prop',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5d1ef968d72a5',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 1,
							'prefix_name' => 1,
						),
						array(
							'key' => 'field_5d1ee8cabfbd5',
							'label' => 'WYSIWYG',
							'name' => 'wysiwyg',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_5d1ee8cdbfbd6',
							'label' => 'Donation Link',
							'name' => 'donation_link',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d1ee8f1bfbd7' => array(
					'key' => 'layout_5d1ee8f1bfbd7',
					'name' => 'latest_events',
					'label' => 'Latest Events',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1efa5774bd8',
							'label' => 'Section Properties',
							'name' => 'sec_prop',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5d1ef968d72a5',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 1,
							'prefix_name' => 1,
						),
						array(
							'key' => 'field_5d1ee983bfbd8',
							'label' => 'Add Events?',
							'name' => 'add_events',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5d1ee9a1bfbd9',
							'label' => 'Number of Events',
							'name' => 'number_of_events',
							'type' => 'button_group',
							'instructions' => 'The number of Events to display on the Front Page.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
							),
							'allow_null' => 0,
							'default_value' => 1,
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d3a68435c25a' => array(
					'key' => 'layout_5d3a68435c25a',
					'name' => 'videos',
					'label' => 'Videos',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d3a68435c25b',
							'label' => 'Section Properties',
							'name' => 'sec_prop',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5d1ef968d72a5',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 1,
							'prefix_name' => 1,
						),
						array(
							'key' => 'field_5d3a68615c262',
							'label' => 'Video Selection',
							'name' => 'video_selection',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'video',
							),
							'taxonomy' => '',
							'filters' => array(
								0 => 'search',
							),
							'elements' => '',
							'min' => '',
							'max' => '',
							'return_format' => 'object',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d22e69964ad9' => array(
					'key' => 'layout_5d22e69964ad9',
					'name' => 'latest_video',
					'label' => 'Latest Video',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d22e6a964adf',
							'label' => 'Please note:',
							'name' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Display - if <b>Active</b> - the latest video from the site\'s YouTube Channel or Playlist. Please find these options in <b>Theme Settings</b> -> <b>Front Page Settings</b>.',
							'new_lines' => 'wpautop',
							'esc_html' => 0,
						),
						array(
							'key' => 'field_5d22e69964ada',
							'label' => 'Section Properties',
							'name' => 'sec_prop',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5d1ef968d72a5',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 1,
							'prefix_name' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5d4f240e033c9' => array(
					'key' => 'layout_5d4f240e033c9',
					'name' => 'buttons',
					'label' => 'Buttons',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d4f240e033cb',
							'label' => 'Section Properties',
							'name' => 'sec_prop',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5d1ef968d72a5',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 1,
							'prefix_name' => 1,
						),
						array(
							'key' => 'field_5d4f242e033cc',
							'label' => 'Buttons',
							'name' => 'buttons',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5d4f238f83a92',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 1,
							'prefix_name' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Content',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'front-page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cfbbd1c5fbd2',
	'title' => 'Link to an Existing Post [BLOCK]',
	'fields' => array(
		array(
			'key' => 'field_5cfcaf857c849',
			'label' => 'Post Links',
			'name' => 'post_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Link',
			'sub_fields' => array(
				array(
					'key' => 'field_5cfbbd261bb93',
					'label' => 'Link to an existing post',
					'name' => 'post_link',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/add-post-in-post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d60eb89957cd',
	'title' => 'Must be logged in',
	'fields' => array(
		array(
			'key' => 'field_5d60eba67bb08',
			'label' => 'Must be logged in message',
			'name' => 'message',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'pg-templates/application-form.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d53d46b7e72e',
	'title' => 'News Custom Archive',
	'fields' => array(
		array(
			'key' => 'field_5d53d47cea964',
			'label' => 'Select News Category',
			'name' => 'news_category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'news_type',
			'field_type' => 'radio',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'pg-templates/news-custom-archive.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cf7d3663395c',
	'title' => 'Page Settings',
	'fields' => array(
		array(
			'key' => 'field_5cf7d37315a16',
			'label' => 'Make page full width',
			'name' => 'full_width',
			'type' => 'true_false',
			'instructions' => 'If <b>Active</b>, the Sidebar will be removed from this page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Active',
			'ui_off_text' => 'Inactive',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d1ef968d72a5',
	'title' => 'Section Properties [CLONE]',
	'fields' => array(
		array(
			'key' => 'field_5d1ef9863512a',
			'label' => 'Active',
			'name' => 'active',
			'type' => 'true_false',
			'instructions' => 'Allows you to deactivate this section without deleting it, thus losing its contents.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d1ef99c3512b',
			'label' => 'Section Title',
			'name' => 'section_title',
			'type' => 'text',
			'instructions' => 'Not required, but sometimes you might want to add a title to a section. E.g.: <b>Court News</b>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => 'Section properties for Flex Builder (on Front Page)',
));

acf_add_local_field_group(array(
	'key' => 'group_5d554d51ba844',
	'title' => 'Single News Post',
	'fields' => array(
		array(
			'key' => 'field_5d554d6bcca15',
			'label' => 'Date published',
			'name' => 'date_published',
			'type' => 'date_picker',
			'instructions' => 'The News Item might have a different date from that published on the website. For e.g. a Press Release might have been released yesterday but you\'re publishing it on the website today. In that case, select yesterday\'s date below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'U',
			'first_day' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'new',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5be1a0ef0d211',
	'title' => 'Social Icons',
	'fields' => array(
		array(
			'key' => 'field_5be1a0fd82c23',
			'label' => 'Social Icons',
			'name' => 'social_icons',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5be1a10482c24',
					'label' => 'Social Icon',
					'name' => 'social_icon',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'fb|facebook' => 'Facebook',
						'tw|twitter' => 'Twitter',
						'gplus|google-plus' => 'Google+',
						'li|linkedin' => 'Linkedin',
						'ins|instagram' => 'Instagram',
						'bnd|bandcamp' => 'Bandcamp',
						'pin|pinterest' => 'Pinterest',
						'vk|vk' => 'Vkontakte',
						'so|stack-overflow' => 'Stack Overflow',
						'yt|youtube' => 'Youtube',
						'slack|slack' => 'Slack',
						'git|github' => 'Github',
						'comm|comments' => 'Comments',
						'email|envelope-o' => 'Email',
						'dribbble|dribbble' => 'Dribbble',
						'reddit|reddit-alien' => 'Reddit',
					),
					'default_value' => array(
					),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'array',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5be1a11d82c25',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c587e9842753',
	'title' => 'Speakers',
	'fields' => array(
		array(
			'key' => 'field_5cf75de452f96',
			'label' => 'Show email',
			'name' => 'show_email',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5cf75dfa52f97',
			'label' => 'Show contact number',
			'name' => 'show_contact_number',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '70',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5cf75a1249140',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5cf75c326e39e',
			'label' => 'Contact Number',
			'name' => 'contact_number',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5cf75bafe2e2d',
			),
			'display' => 'group',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5c587ea5559ee',
			'label' => 'Artist Website',
			'name' => 'artist_website',
			'type' => 'url',
			'instructions' => 'Must start with <b>https://</b> or <b>https://</b>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g. https://google.com',
		),
		array(
			'key' => 'field_5cf7731a6a603',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => 'Maximum dimensions: 500 x 500px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => 500,
			'max_height' => 500,
			'max_size' => '',
			'mime_types' => 'jpeg,jpg,png',
		),
		array(
			'key' => 'field_5cf77ea798fce',
			'label' => 'Short Bio',
			'name' => 'short_bio',
			'type' => 'textarea',
			'instructions' => '300 char. max.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 500,
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'speaker',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d6fffed88fc5',
	'title' => 'Statute',
	'fields' => array(
		array(
			'key' => 'field_5d700108c87f5',
			'label' => 'Article',
			'name' => 'article',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5d70011fc87f6',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Article',
			'sub_fields' => array(
				array(
					'key' => 'field_5d70011fc87f6',
					'label' => 'Article Title',
					'name' => 'article_title',
					'type' => 'text',
					'instructions' => 'Please note that the article number will be automatically added.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d700147c87f7',
					'label' => 'Headings',
					'name' => 'headings',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5d700b144e973',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add Heading',
					'sub_fields' => array(
						array(
							'key' => 'field_5d700b144e973',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5d7004d8c87f8',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'wysiwyg',
							'instructions' => 'Please note that the heading numbers will be automatically added.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5d700d6e46721',
							'label' => 'Sub-heading numbering style',
							'name' => 'num_style',
							'type' => 'button_group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'letter' => 'a)',
								'roman' => 'iv.',
							),
							'allow_null' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array(
							'key' => 'field_5d7004fdc87f9',
							'label' => 'Sub-headings',
							'name' => 'subheadings',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5d700b204e974',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Sub-heading',
							'sub_fields' => array(
								array(
									'key' => 'field_5d700b204e974',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5d700509c87fa',
									'label' => 'Sub-heading',
									'name' => 'subheading',
									'type' => 'wysiwyg',
									'instructions' => 'Please note that the sub-heading numbers will be automatically added.',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
							),
						),
						array(
							'key' => 'field_5d736f17551f4',
							'label' => 'Heading Cont\'d',
							'name' => 'heading_contd',
							'type' => 'wysiwyg',
							'instructions' => 'Please note that the heading numbers will be automatically added.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/add-statute',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cf6a2c02a314',
	'title' => 'Theme Settings',
	'fields' => array(
		array(
			'key' => 'field_5d21a61287a1f',
			'label' => 'Front Page Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d21a72587a21',
			'label' => 'YouTube API Key',
			'name' => 'youtube_api_key',
			'type' => 'password',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5d21a61f87a20',
			'label' => 'Get latest video from...',
			'name' => 'get_latest_video_from',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'channel' => 'Channel',
				'playlist' => 'Playlist',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5d21a8c8504de',
			'label' => 'Channel ID',
			'name' => 'channel_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d21a61f87a20',
						'operator' => '==',
						'value' => 'channel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d21a8e4504df',
			'label' => 'Playlist ID',
			'name' => 'playlist_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d21a61f87a20',
						'operator' => '==',
						'value' => 'playlist',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cfcbefdf3978',
			'label' => 'Blog List Properties',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cf6a43d91ba7',
			'label' => 'Number of posts',
			'name' => 'num_of_posts',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				6 => '6',
				9 => '9',
				12 => '12',
			),
			'allow_null' => 0,
			'default_value' => 12,
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cf6a2ccbddcb',
			'label' => 'Number of columns',
			'name' => 'num_of_cols',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cf6a43d91ba7',
						'operator' => '==',
						'value' => '12',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				2 => '2',
				3 => '3',
				4 => '4',
				6 => '6',
			),
			'allow_null' => 0,
			'default_value' => 4,
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cf6a4d736887',
			'label' => 'Number of columns',
			'name' => 'num_of_cols',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cf6a43d91ba7',
						'operator' => '==',
						'value' => '9',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				3 => '3',
			),
			'allow_null' => 0,
			'default_value' => 3,
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cf6a4fb36888',
			'label' => 'Number of columns',
			'name' => 'num_of_cols',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cf6a43d91ba7',
						'operator' => '==',
						'value' => '6',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				2 => '2',
				3 => '3',
				6 => '6',
			),
			'allow_null' => 0,
			'default_value' => 3,
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5d62522099c2a',
			'label' => 'Footer Buttons',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d62525999c2b',
			'label' => 'Buttons',
			'name' => 'buttons',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5d4f238f83a92',
			),
			'display' => 'seamless',
			'layout' => 'block',
			'prefix_label' => 1,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5d62acc449446',
			'label' => 'Bank Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d62ad0749448',
			'label' => 'Banks',
			'name' => 'banks',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d62acd449447',
					'label' => 'Bank',
					'name' => 'bank',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'aps' => 'APS',
						'hsbc' => 'HSBC',
						'bov' => 'BOV',
						'banif' => 'Banif',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'array',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d62ad2b4944a',
					'label' => 'Account No.',
					'name' => 'account_no',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d62ad404944b',
					'label' => 'IBAN No.',
					'name' => 'iban_no',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d62ad524944c',
					'label' => 'Note',
					'name' => 'note',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5d6fed9ba6c98',
			'label' => 'Social Icons',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d6feda5a6c99',
			'label' => 'Social Icons',
			'name' => 'social_icons',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5be1a0ef0d211',
			),
			'display' => 'group',
			'layout' => 'block',
			'prefix_label' => 1,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5d6ff2dd82274',
			'label' => 'Contact Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d6ff3ba32454',
			'label' => 'Contact Details',
			'name' => 'contact_details',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5d6ff31b33198',
			),
			'display' => 'group',
			'layout' => 'block',
			'prefix_label' => 1,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5d7122bb7d05e',
			'label' => 'Contact Form',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d7122c67d05f',
			'label' => 'Main Contact Form',
			'name' => 'main_cf',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'wpcf7_contact_form',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c584bd8d45bc',
	'title' => 'Venues',
	'fields' => array(
		array(
			'key' => 'field_5c586df8d440a',
			'label' => 'Venue Address',
			'name' => 'venue_address',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c586e05d440b',
			'label' => 'Venue City',
			'name' => 'venue_city',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c586e0ed440c',
			'label' => 'Venue State/Provence',
			'name' => 'venue_state_provence',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c586e25d440d',
			'label' => 'Venue Postal Code',
			'name' => 'venue_postal_code',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c586e2fd440e',
			'label' => 'Venue Country',
			'name' => 'venue_country',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'AF' => 'Afghanistan',
				'AX' => 'Aland Islands',
				'AL' => 'Albania',
				'DZ' => 'Algeria',
				'AS' => 'American Samoa',
				'AD' => 'Andorra',
				'AO' => 'Angola',
				'AI' => 'Anguilla',
				'AQ' => 'Antarctica',
				'AG' => 'Antigua and Barbuda',
				'AR' => 'Argentina',
				'AM' => 'Armenia',
				'AW' => 'Aruba',
				'AU' => 'Australia',
				'AT' => 'Austria',
				'AZ' => 'Azerbaijan',
				'BS' => 'Bahamas',
				'BH' => 'Bahrain',
				'BD' => 'Bangladesh',
				'BB' => 'Barbados',
				'BY' => 'Belarus',
				'BE' => 'Belgium',
				'BZ' => 'Belize',
				'BJ' => 'Benin',
				'BM' => 'Bermuda',
				'BT' => 'Bhutan',
				'BO' => 'Bolivia',
				'BQ' => 'Bonaire, Saint Eustatius and Saba',
				'BA' => 'Bosnia and Herzegovina',
				'BW' => 'Botswana',
				'BV' => 'Bouvet Island',
				'BR' => 'Brazil',
				'IO' => 'British Indian Ocean Territory',
				'BN' => 'Brunei Darussalam',
				'BG' => 'Bulgaria',
				'BF' => 'Burkina Faso',
				'BI' => 'Burundi',
				'KH' => 'Cambodia',
				'CM' => 'Cameroon',
				'CA' => 'Canada',
				'CV' => 'Cape Verde',
				'KY' => 'Cayman Islands',
				'CF' => 'Central African Republic',
				'TD' => 'Chad',
				'CL' => 'Chile',
				'CN' => 'China',
				'CX' => 'Christmas Island',
				'CC' => 'Cocos (Keeling) Islands',
				'CO' => 'Colombia',
				'KM' => 'Comoros',
				'CG' => 'Congo',
				'CD' => 'Congo (DR)',
				'CK' => 'Cook Islands',
				'CR' => 'Costa Rica',
				'CI' => 'Cote d\'Ivoire',
				'HR' => 'Croatia',
				'CU' => 'Cuba',
				'CW' => 'Curacao',
				'CY' => 'Cyprus',
				'CZ' => 'Czech Republic',
				'DK' => 'Denmark',
				'DJ' => 'Djibouti',
				'DM' => 'Dominica',
				'DO' => 'Dominican Republic',
				'EC' => 'Ecuador',
				'EG' => 'Egypt',
				'SV' => 'El Salvador',
				'GQ' => 'Equatorial Guinea',
				'ER' => 'Eritrea',
				'EE' => 'Estonia',
				'ET' => 'Ethiopia',
				'FK' => 'Falkland Islands (Malvinas)',
				'FO' => 'Faroe Islands',
				'FJ' => 'Fiji',
				'FI' => 'Finland',
				'FR' => 'France',
				'GF' => 'French Guiana',
				'PF' => 'French Polynesia',
				'TF' => 'French Southern Territories',
				'GA' => 'Gabon',
				'GM' => 'Gambia',
				'GE' => 'Georgia',
				'DE' => 'Germany',
				'GH' => 'Ghana',
				'GI' => 'Gibraltar',
				'GR' => 'Greece',
				'GL' => 'Greenland',
				'GD' => 'Grenada',
				'GP' => 'Guadeloupe',
				'GU' => 'Guam',
				'GT' => 'Guatemala',
				'GG' => 'Guernsey',
				'GN' => 'Guinea',
				'GW' => 'Guinea-Bissau',
				'GY' => 'Guyana',
				'HT' => 'Haiti',
				'HM' => 'Heard and McDonald Islands',
				'VA' => 'Holy See (Vatican City State)',
				'HN' => 'Honduras',
				'HK' => 'Hong Kong',
				'HU' => 'Hungary',
				'IS' => 'Iceland',
				'IN' => 'India',
				'ID' => 'Indonesia',
				'IR' => 'Iran',
				'IQ' => 'Iraq',
				'IE' => 'Ireland',
				'IM' => 'Isle of Man',
				'IL' => 'Israel',
				'IT' => 'Italy',
				'JM' => 'Jamaica',
				'JP' => 'Japan',
				'JE' => 'Jersey',
				'JO' => 'Jordan',
				'KZ' => 'Kazakhstan',
				'KE' => 'Kenya',
				'KI' => 'Kiribati',
				'KP' => 'Korea (North)',
				'KR' => 'Korea (South)',
				'KW' => 'Kuwait',
				'KG' => 'Kyrgyzstan',
				'LA' => 'Laos',
				'LV' => 'Latvia',
				'LB' => 'Lebanon',
				'LS' => 'Lesotho',
				'LR' => 'Liberia',
				'LY' => 'Libya',
				'LI' => 'Liechtenstein',
				'LT' => 'Lithuania',
				'LU' => 'Luxembourg',
				'MO' => 'Macao',
				'MK' => 'Macedonia',
				'MG' => 'Madagascar',
				'MW' => 'Malawi',
				'MY' => 'Malaysia',
				'MV' => 'Maldives',
				'ML' => 'Mali',
				'MT' => 'Malta',
				'MH' => 'Marshall Islands',
				'MQ' => 'Martinique',
				'MR' => 'Mauritania',
				'MU' => 'Mauritius',
				'YT' => 'Mayotte',
				'MX' => 'Mexico',
				'FM' => 'Micronesia',
				'MD' => 'Moldova',
				'MC' => 'Monaco',
				'MN' => 'Mongolia',
				'ME' => 'Montenegro',
				'MS' => 'Montserrat',
				'MA' => 'Morocco',
				'MZ' => 'Mozambique',
				'MM' => 'Myanmar',
				'NA' => 'Namibia',
				'NR' => 'Nauru',
				'NP' => 'Nepal',
				'NL' => 'Netherlands',
				'NC' => 'New Caledonia',
				'NZ' => 'New Zealand',
				'NI' => 'Nicaragua',
				'NE' => 'Niger',
				'NG' => 'Nigeria',
				'NU' => 'Niue',
				'NF' => 'Norfolk Island',
				'MP' => 'Northern Mariana Islands',
				'NO' => 'Norway',
				'OM' => 'Oman',
				'PK' => 'Pakistan',
				'PW' => 'Palau',
				'PS' => 'Palestine',
				'PA' => 'Panama',
				'PG' => 'Papua New Guinea',
				'PY' => 'Paraguay',
				'PE' => 'Peru',
				'PH' => 'Philippines',
				'PN' => 'Pitcairn',
				'PL' => 'Poland',
				'PT' => 'Portugal',
				'PR' => 'Puerto Rico',
				'QA' => 'Qatar',
				'RE' => 'Reunion',
				'RO' => 'Romania',
				'RU' => 'Russian Federation',
				'RW' => 'Rwanda',
				'BL' => 'Saint Barthelemy',
				'SH' => 'Saint Helena',
				'KN' => 'Saint Kitts and Nevis',
				'LC' => 'Saint Lucia',
				'MF' => 'Saint Martin',
				'PM' => 'Saint Pierre and Miquelon',
				'VC' => 'Saint Vincent and the Grenadines',
				'WS' => 'Samoa',
				'SM' => 'San Marino',
				'ST' => 'Sao Tome and Principe',
				'SA' => 'Saudi Arabia',
				'SN' => 'Senegal',
				'RS' => 'Serbia',
				'SC' => 'Seychelles',
				'SL' => 'Sierra Leone',
				'SG' => 'Singapore',
				'SX' => 'Sint Maarten',
				'SK' => 'Slovakia',
				'SI' => 'Slovenia',
				'SB' => 'Solomon Islands',
				'SO' => 'Somalia',
				'ZA' => 'South Africa',
				'GS' => 'South Georgia and South Sandwich Islands',
				'ES' => 'Spain',
				'LK' => 'Sri Lanka',
				'SD' => 'Sudan',
				'SS' => 'South Sudan',
				'SR' => 'Suriname',
				'SJ' => 'Svalbard and Jan Mayen',
				'SZ' => 'Swaziland',
				'SE' => 'Sweden',
				'CH' => 'Switzerland',
				'SY' => 'Syria',
				'TW' => 'Taiwan',
				'TJ' => 'Tajikistan',
				'TZ' => 'Tanzania',
				'TH' => 'Thailand',
				'TL' => 'Timor-Leste',
				'TG' => 'Togo',
				'TK' => 'Tokelau',
				'TO' => 'Tonga',
				'TT' => 'Trinidad and Tobago',
				'TN' => 'Tunisia',
				'TR' => 'Turkey',
				'TM' => 'Turkmenistan',
				'TC' => 'Turks and Caicos Islands',
				'TV' => 'Tuvalu',
				'UG' => 'Uganda',
				'UA' => 'Ukraine',
				'AE' => 'United Arab Emirates',
				'UK' => 'United Kingdom',
				'US' => 'United States',
				'UM' => 'United States Minor Outlying Islands',
				'UY' => 'Uruguay',
				'UZ' => 'Uzbekistan',
				'VU' => 'Vanuatu',
				'VE' => 'Venezuela',
				'VN' => 'Vietnam',
				'VG' => 'Virgin Islands (British)',
				'VI' => 'Virgin Islands (U.S.)',
				'WF' => 'Wallis and Futuna',
				'EH' => 'Western Sahara',
				'YE' => 'Yemen',
				'ZM' => 'Zambia',
				'ZW' => 'Zimbabwe',
			),
			'default_value' => array(
				0 => 'BE',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'array',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c586e78d440f',
			'label' => 'Venue Website',
			'name' => 'venue_website',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c586e81d4410',
			'label' => 'Venue Phone',
			'name' => 'contact_number',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_5cf75bafe2e2d',
			),
			'display' => 'group',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 1,
		),
		array(
			'key' => 'field_5cdba9068567a',
			'label' => 'Venue Map',
			'name' => 'venue_map',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '51.082572',
			'center_lng' => '3.5744034',
			'zoom' => 11,
			'height' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'venue',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d1f0cb972e0d',
	'title' => 'Videos',
	'fields' => array(
		array(
			'key' => 'field_5d1f0d3f5f08a',
			'label' => 'Embed Type',
			'name' => 'embedding_type',
			'type' => 'radio',
			'instructions' => '<strong>URL e.g.:</strong> \'https://youtu.be/ibNZVROabN8\'
<br>
<strong>Embed Code e.g.:</strong> &#x3C;iframe width=&#x22;1280&#x22; height=&#x22;720&#x22; src=&#x22;https://www.youtube.com/embed/ibNZVROabN8&#x22; frameborder=&#x22;0&#x22; allow=&#x22;accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture&#x22; allowfullscreen&#x3E;&#x3C;/iframe&#x3E;\'',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'url' => 'URL',
				'embed' => 'Embed Code',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5d1f0d675f08b',
			'label' => 'URL',
			'name' => 'url',
			'type' => 'oembed',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d1f0d3f5f08a',
						'operator' => '==',
						'value' => 'url',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
		array(
			'key' => 'field_5d1f0d7f5f08c',
			'label' => 'Embed Code',
			'name' => 'embed_code',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d1f0d3f5f08a',
						'operator' => '==',
						'value' => 'embed',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'video',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d5572b5ccb39',
	'title' => 'Videos Custom Archive',
	'fields' => array(
		array(
			'key' => 'field_5d5572b607ae3',
			'label' => 'Select Videos Category',
			'name' => 'videos_category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'video_type',
			'field_type' => 'radio',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'pg-templates/videos-custom-archive.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;